name: DevSecOps Security Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  security-checks:
    name: Run Security Scans
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    ##########################
    # Semgrep (SAST)
    ##########################
    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: p/java
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    ##########################
    # Gitleaks (Secrets scan)
    ##########################
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      with:
        args: "--verbose --redact"

    ##########################
    # OWASP Dependency-Check (Manual CLI)
    ##########################
    - name: Download Dependency-Check CLI
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.6/dependency-check-9.0.6-release.zip
        unzip dependency-check-9.0.6-release.zip -d dc
        chmod +x dc/dependency-check/bin/dependency-check.sh

    - name: Run Dependency-Check
      run: |
        dc/dependency-check/bin/dependency-check.sh \
          --project "spring-petclinic" \
          --scan . \
          --format HTML \
          --out reports

    - name: Upload Dependency-Check report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: reports/dependency-check-report.html

    ##########################
    # Snyk Scan
    ##########################
    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk to check for vulnerabilities
      run: snyk test --all-projects --json-file-output=snyk-report.json || true

    - name: Upload Snyk report
      uses: actions/upload-artifact@v4
      with:
        name: snyk-report
        path: snyk-report.json
